### ISSUE TITLE
Both sslnotify.me and sslexpired.info are down

### ISSUE THREAD

**Issue by raoulbhatia** [shaftoe/sslnotifyme#1]
Hi!

I assume this is known, but I'd still like to report that both sslnotify.me and sslexpired.info are down.

Q. Is there any replacement service that you are using now, i.e. for yourself?

Thanks,
Raoul

**Comment by shaftoe** [comment]
Hello @raoulbhatia , thanks for the report.
Actually I just lost interest in the project and decided not to renew the domain nor keep up the infrastructure. It should be fairly easy to setup the whole thing following the README though.
I'm not aware of any similar service, I'm hosting all my projects on platforms like Netlify or AWS (using ACM service to manage certificates) and I trust them to keep the certs up to date.
Anyway, I'll update the README letting everybody know that the project is discontinued, thanks for the reminder

**Comment by shaftoe** [comment]
Added a not to README with https://github.com/shaftoe/sslnotifyme/commit/fa2e92f4894fe27a304633c78cf547a9b17b7fe4. Closing the issue

**Comment by raoulbhatia** [comment]
Thanks for the quick update.  Now, I'll just need to find time to get this up and running 😅
